  name: Parent Workflow

  on:
    workflow_dispatch:
    pull_request:
      branches:
        - main
      types: [opened]

  jobs:
      testJob:
          runs-on: ubuntu-latest
          steps:
              - name: Checkout
                uses: actions/checkout@v4
              
              - name: create a test file
                run: echo "Hello World" > test.txt
              
              - name: upload test file
                uses: actions/upload-artifact@v4
                with:
                  name: test-file
                  path: test.txt
              
              - name: Set branch output
                id: set-branch
                run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV